/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/3D/models/site-mixer-1.glb --types --output src/types/generated-gltf.tsx 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    handheld: THREE.Mesh
    button1: THREE.Mesh
    button2: THREE.Mesh
    button3: THREE.Mesh
    button4: THREE.Mesh
    button5: THREE.Mesh
    button6: THREE.Mesh
    knobl: THREE.Mesh
    knobc: THREE.Mesh
    knobr: THREE.Mesh
    button1_emission: THREE.Mesh
    button2_emission: THREE.Mesh
    button3_emission: THREE.Mesh
    screens: THREE.Mesh
  }
  materials: {
    bake: THREE.MeshStandardMaterial
    emission: THREE.MeshStandardMaterial
    screen: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/site-mixer-1.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.handheld.geometry} material={materials.bake} position={[0, 0, -0.001]} />
      <mesh geometry={nodes.button1.geometry} material={materials.bake} position={[0.636, -0.157, 0.054]} />
      <mesh geometry={nodes.button2.geometry} material={materials.bake} position={[0.759, -0.156, 0.055]} />
      <mesh geometry={nodes.button3.geometry} material={materials.bake} position={[0.893, -0.158, 0.055]} />
      <mesh geometry={nodes.button4.geometry} material={materials.bake} position={[0.635, -0.045, 0.049]} />
      <mesh geometry={nodes.button5.geometry} material={materials.bake} position={[0.764, -0.045, 0.049]} />
      <mesh geometry={nodes.button6.geometry} material={materials.bake} position={[0.892, -0.045, 0.049]} />
      <mesh geometry={nodes.knobl.geometry} material={materials.bake} position={[0.631, 0.076, 0.081]} />
      <mesh geometry={nodes.knobc.geometry} material={materials.bake} position={[0.766, 0.076, 0.081]} />
      <mesh geometry={nodes.knobr.geometry} material={materials.bake} position={[0.901, 0.076, 0.081]} />
      <mesh geometry={nodes.button1_emission.geometry} material={materials.emission} position={[0.636, -0.157, 0.054]} />
      <mesh geometry={nodes.button2_emission.geometry} material={materials.emission} position={[0.759, -0.156, 0.055]} />
      <mesh geometry={nodes.button3_emission.geometry} material={materials.emission} position={[0.893, -0.158, 0.055]} />
      <mesh geometry={nodes.screens.geometry} material={materials.screen} position={[0, 0, -0.001]} />
    </group>
  )
}

useGLTF.preload('/site-mixer-1.glb')
