export const items = [
    {
        id: "1",
        href: "/images/a.jpg",
        aspect: "portrait",
        title: "",
        description: "",
    },
    {
        id: "2",
        href: "/images/b.jpg",
        aspect: "landscape",
        title: "",
        description: "",
    },
    {
        id: "3",
        href: "/images/c.jpg",
        aspect: "landscape",
        title: "",
        description: "",
    },
    {
        id: "4",
        href: "/images/d.jpg",
        aspect: "portrait",
        title: "",
        description: "",
    },
    {
        id: "5",
        href: "/images/e.jpg",
        aspect: "portrait",
        title: "",
        description: "",
    },
    {
        id: "6",
        href: "/images/f.jpg",
        aspect: "landscape",
        title: "",
        description: "",
    },
    {
        id: "7",
        href: "/images/g.jpg",
        aspect: "landscape",
        title: "",
        description: "",
    },
    {
        id: "8",
        href: "/images/h.jpg",
        aspect: "portrait",
        title: "",
        description: "",
    },
    {
        id: "9",
        href: "/images/a.jpg",
        aspect: "portrait",
        title: "",
        description: "",
    },
    {
        id: "10",
        href: "/images/b.jpg",
        aspect: "landscape",
        title: "",
        description: "",
    },
    {
        id: "11",
        href: "/images/c.jpg",
        aspect: "landscape",
        title: "",
        description: "",
    },
    {
        id: "12",
        href: "/images/d.jpg",
        aspect: "portrait",
        title: "",
        description: "",
    },
    {
        id: "13",
        href: "/images/e.jpg",
        aspect: "portrait",
        title: "",
        description: "",
    },
    {
        id: "14",
        href: "/images/f.jpg",
        aspect: "landscape",
        title: "",
        description: "",
    },
    {
        id: "15",
        href: "/images/g.jpg",
        aspect: "landscape",
        title: "",
        description: "",
    },
    {
        id: "16",
        href: "/images/h.jpg",
        aspect: "portrait",
        title: "",
        description: "",
    },
    {
        id: "17",
        href: "/images/h.jpg",
        aspect: "portrait",
        title: "",
        description: "",
    },
    {
        id: "18",
        href: "/images/h.jpg",
        aspect: "portrait",
        title: "",
        description: "",
    },
]